replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.28.1-alpine"
  pullPolicy: IfNotPresent

cluster:
  name: unknown-cluster
  apiServer: unknown
  environment: ACM-managed OpenShift cluster

application:
  name: OpenShift Portability Demo
  version: "5.0.0"
  message: One application definition. Placement-driven across OpenShift clusters.
  gitRepository: git@github.com:h8x0rd/openshift-portability-demo.git
  gitRevision: main

service:
  port: 8080

route:
  enabled: true
  tls:
    termination: edge

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 2
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
